ALTER TABLE "OT" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'PENDING_APPROVAL';
ALTER TABLE "OT" ADD COLUMN "approvedById" TEXT REFERENCES "Employee"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "OT" ADD COLUMN "approvedAt" DATETIME;

CREATE INDEX "OT_status_idx" ON "OT"("status");
